name: Deploy to Arweave

on:
  push:
    branches:
      - main # Trigger the deployment when there's a push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.18.0" # Using Node.js version 18.18.0

      - name: Install Dependencies
        run: npm install

      - name: Decode Arweave Wallet File
        run: echo '${{ secrets.ARWEAVE_WALLET_ENCODED }}' | base64 -d > wallet.json

      - name: Deploy to Arweave
        run: echo CONFIRM | npm run deploy | tee deploy_output.txt

        
      - name: Set Execute Permission for Script
        run: chmod +x ./update_readme.sh

      - name: Update README with Arweave Link
        run: ./update_readme.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Your step to commit and push changes
      - name: Commit and Push Updated README
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with Arweave deployment link"
          git push
