name: Deploy to Arweave

on:
  push:
    branches:
      - main  # Trigger the deployment when there's a push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'  # Using Node.js version 18.18.0

      - name: Install Dependencies
        run: npm install

      - name: Decode Arweave Wallet File
        run: echo '${{ secrets.ARWEAVE_WALLET_ENCODED }}' | base64 -d > wallet.json

      - name: Deploy to Arweave
        run: echo CONFIRM | npm run deploy

      - name: Remove Arweave Wallet File
        run: rm wallet.json
